#!/usr/bin/env python3
import csv
import os
from datetime import date
print(
"""
 =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-   | *
 |  ____    ____       _     __   __  ____                         | '
 L | __ )  |  _ \     / \    \ \ / / / ___|       _ __    _   _    |  *'
 | |  _ \  | | | |   / _ \    \ V /  \___ \      | '_ \  | | | |   |
 | | |_) | | |_| |  / ___ \    | |    ___) |  _  | |_) | | |_| |   | ' .
 ] |____/  |____/  /_/   \_\   |_|   |____/  (_) | .__/   \__, |   |
 |                                               |_|      |___/   |   ' 
 =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-   |.
"""
)

entries = []
incomingBdays = []
today = date.today()
homeDir = os.path.expanduser("~")

# read bday entries
with open(homeDir + "/knowledge-tree/bdays.csv", newline="") as csvfile:
    reader = csv.reader(csvfile, delimiter=",", quotechar="|")
    for row in reader:
        entries.append(row)

# parse bday entries
for row in entries:
    name = row[1].strip()
    bday = date.fromisoformat(row[0])
    nextBday = bday.replace(year=today.year)
    distance = abs(nextBday - today)
    if distance.days <= 30:
        incomingBdays.append((nextBday, (bday, name)))

for _, [bday, name] in sorted(incomingBdays):
    print(bday, name)
