#!/bin/zsh
# reminds user of birthdays happening in the next 30 days
zmodload zsh/mapfile
# change this path to locate your stored birthdays
# in the format: 05/12 , 2000 , John Smith
FNAME=/home/$USER/knowledge-tree/bdays.csv
FLINES=( "${(f)mapfile[$FNAME]}" )
LIST="${mapfile[$FNAME]}" # Not required unless stuff uses it
integer POS=1             # Not required unless stuff uses it
integer SIZE=$#FLINES     # Number of lines, not required unless stuff uses it
print "=-=-=-=-=-=-=-=-=-"
print "[ UPCOMING BDAYS ]"
print "=-=-=-=-=-=-=-=-=-"
for ITEM in $FLINES
    do bday=${ITEM[(ws: , :)1]} # split string by commas and get birthday parameter
    target_time=`date -d ${bday} +%s` #convert **/**/**** birthday to time from epoch
    today_time=`date +%s`
    diff=$(((target_time - today_time)/3600)) # number of hours birthday is from today
    if [[ $diff -lt "505" && $diff -ge "-48" ]]
    then
        name=${ITEM[(ws: , :)3]} # split string by commas and get birthday parameter
        bday=`date -d ${bday} +%a.%b.%d`
        print ${name} "---" '('${bday}')'
    fi
    (( POS++ ))
done
